### ISSUE TITLE
Optimal Downsampling Value

### ISSUE THREAD

**Issue by carabidus** [jcolomb/CeTrAn#10]
Assuming that the data is captured at 30 frames per second, what is a good target rate for downsampling to reduce noise?

**Comment by jcolomb** [comment]
buritrack is only getting data when the point is moving. CeTrAn is resampling the data, I think at 10 Hz. Then it cancel any movement smaller than x mm (0.8 is the default value I think).
Some of the analysis requires data with a fixed time difference between points, I do not remember if 10 Hz is required or whether up or down sampling could make a difference.
