### ISSUE TITLE
Occupancy in each quadrant

### ISSUE THREAD

**Issue by chiser** [jcolomb/CeTrAn#2]
Hi Julien! I wanted to ask you something because I´m really stucked after so much search. I´ve made a code in R that is able to load the Buridan´s .dat files and then count how much time is spent in each quadrant. The problem is trying to put it together with your CeTrAn software. There are three important variables (that I noticed) that I need to call from the workspace:
- Arena center coordinates: which I think is well solved with params[[i]$ARENA_CENTER_X (or Y).
- The table with the X-Y coordinates as in .dat files: so that I can compare to the center reference. I´m not able to find any variable that contains these coordinates. I find others (eg. xy_table) with modified coordinates, I guess it is converted either into mm or is the result of the "traj" processing which I don´t find that trivial (I did read about adehabitat).
- The table with the time as in .dat files: so that I can make cumulative sums of time depending on the quadrant the flies are. I found several variables with information of total time of experiment, or computer time, ... and after all Im not able to find an appropiate one with a table of the experiment time corresponding to fly position.

Any ideas? Is there a way to look better ver the existing variables? Before I just went searching script by script for variables, now I load and old session workspace but eventhough it doesn´t countain variables of all scripts.

From that you just told me: the trajectories are first modified to have the center at 0:0, the distance in mm and a regular time interval between points. What you want to do is a 3 lines code after that conversion.

Now I paste the code I made with some stuff copied from other scripts from you (that I think are important although I don´t fully understand them) and what I introduced. Is the time units the result of a 10Hz sampling so that I can take each time unit as a 100ms?

```
                                                   R CODE
```

message ("starting occupancyquadrant.r") # for debugging in rgg
# get the x,y coordinates of all the individuals

xy_table = data.frame()
for (i in c(1:nrow(id_table))) {
    itraj = traj[id(traj)==id_table$id[i]]
    }
#### center data

```
x=itraj[[1]]$x - env[[i]]$cx
y=itraj[[1]]$y - env[[i]]$cy
```
# delete paints when the fly is not moving

```
if (g_supress_paints) {
    dx = itraj[[1]]$dx
    dy = itraj[[1]]$dy
    dx[is.na(dx)] = 0   
    dy[is.na(dy)] = 0
    new_x = c()
    new_y = c() 
    moved_distance = 0
    for (j in c(1:length(x))) {
        moved_distance = moved_distance + sqrt(dx[j]*dx[j]+dy[j]*dy[j])
        # if the fly moved 2 mm, add a point to xy_table
        if (moved_distance> g_treshold) {
            new_x = c(new_x,x[j])
            new_y = c(new_y,y[j])
            moved_distance = 0
        }
    }
} else {
    new_x = x
    new_y = y
     }



xy = data.frame(x=new_x,y=new_y)    
id = rep(id_table$id[i],nrow(xy))
group = rep(id_table$group[i],nrow(xy))
xy_table = rbind(xy_table,data.frame(xy,id,group))
```
# establishing what is each quadrant

  upperright =  xy_table$x > 0 & xy_table$y > 0 
  upperleft =  xy_table$x < 0 & xy_table$y > 0
  lowerright =  xy_table$x > 0 & xy_table$y < 0
  lowerleft =  xy_table$x < 0 & xy_table$y < 0
# summing up times for each quadrant.
# If time is counted in equal steps one can just add a simple uds. But what are these units?

calculation <- function (id_table) {
  upperrightquadrant = 0
  upperleftquadrant = 0
  lowerrightquadrant = 0
  lowerleftquadrant = 0
  for (i in c(1:nrow(id_table))){
      if (upperright[i]) upperrightquadrant <- upperrightquadrant + 1
      if (upperleft[i]) upperleftquadrant <- upperleftquadrant + 1
      if (lowerright[i]) lowerrightquadrant <- lowerrightquadrant + 1
      if (lowerleft[i]) lowerleftquadrant <- lowerleftquadrant + 1
  }

  list(upperrightquadrant = upperrightquadrant, upperleftquadrant = upperleftquadrant,
       lowerrightquadrant = lowerrightquadrant, lowerleftquadrant = lowerleftquadrant)
}
output = calculation(id_table)

print(xy_table)        # input
print(output)   # output
# paint the diagram for each group

group_names = levels(id_table$group)

occupancy_table = data.frame(output,group=id_table$group)
occupancy_mtable = create.mean.table(occupancy_table,group_ids)

mybarplot(occupancy_mtable$means$output,occupancy_mtable$ses$output, rownames = group_ids,
    main="Occupancy box plot",ylab="Total time [s]", ylim = c(0,ylim_output))
# mybarplot <- function(means,sds,rownames,...) {
# mp <- barplot2(means,plot.grid = TRUE,names.arg=rownames,
# ci.l = means-sds, ci.u = means+sds,plot.ci = TRUE,...)
# box()
# }

**Comment by jcolomb** [comment]
hi Christian,

First data are already centered after loading, in multiplefileloader.r script:
    if (CENTERHERE) {
	env <- lapply(params, create.env.vars.center)
	}else {env <- lapply(params, create.env.vars)}

and later in function load.buridan.data
     	if (center) {
		data$x = data$x-as.numeric(params$ARENA_CENTER_X)
		data$y = data$y-as.numeric(params$ARENA_CENTER_Y)
				}

so you do not need to center it.

time is calculated in equal steps (the data is transformed to achieve this). you can see it by looking at the dt value for the trajectories (0,1s for all points). 

There seems to be a problem with your loops: you are not looping for each trajectory (each fly + each burst for each fly). in your "upperright[i])", i is referring to the row in id_table, which is one fly, while upperright is a part of xytable caculated already for one fly, or did I miss something ?? 

there is probably an easier way: try to look at the thigmotaxis.r code and modify it for your purpose: there it can calculate the proportion of time spent in the different positions (center or outer ring) while taking only moving points, only sitting points or all points... You should just need to define the positions differently , twist the code because you have 4 and not 2 areas and it should be work...

PS: I would first try box plots and not bar plots, then you can see if the data is normally distributed...

**Comment by chiser** [comment]
Hi Julien,

I have some hooked flies and everything ready to try... so if whenever you have time you could maybe help me a bit through skype.

Best,

Christian

  
    
    
  
  
 		 	   		  =
