### ISSUE TITLE
XML content does not seem to be XML

### ISSUE THREAD

**Issue by brembs** [jcolomb/CeTrAn#3]
What does this error message mean?

**Comment by jcolomb** [comment]
The error state that the read file does not have an XML structure. Unfortunately, the same message appear if no file is read. This latter case is the most common: the file name in the group text file is probably written with a typo eror, or you forgot to add the suffix ".xml" to the file name.

On 7 April 2015 18:14:51 CEST, "Björn Brembs" <notifications@github.com> wrote:
>What does this error message mean?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jcolomb/CeTrAn/issues/3

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.
