### ISSUE TITLE
Cannot Unzip "CeTrAn4.03.zip"

### ISSUE THREAD

**Issue by carabidus** [jcolomb/CeTrAn#4]
Below is the error message when I attempt to unzip the archive. Then, I noticed that the file name has 2 periods, so I eliminated one of them by renaming the file. Still no luck... Please advise and thank you.
![image](https://cloud.githubusercontent.com/assets/16169756/11610032/067316ec-9b65-11e5-9948-0ee8ff806bac.png)

**Comment by brembs** [comment]
It works just fine for me. Just give it time to download as there are a lot of example data with the package.

**Comment by carabidus** [comment]
Got it to unzip! Thanks for the reply... This software package and accompanying analysis tools are just superb! I am a first year PhD student in behavioral ecology and I am embarking upon some preliminary open-field trials with wolf spiders. Although I have a fundamental grasp of R, I will probably have more questions as I delve deeper into the R resources that you and your research team put together.
