### ISSUE TITLE
Rggrunner Starts Then Shuts Down

### ISSUE THREAD

**Issue by carabidus** [jcolomb/CeTrAn#5]
Greetings,

I got Buritrack to capture real-time data with wolf spiders, and now I would like to use the accompanying software for analysis.

I get this window for a few seconds when I run Rrrrunner, but then the program shuts down:
![image](https://cloud.githubusercontent.com/assets/16169756/11759053/5d37a278-a041-11e5-8010-f32387583803.png)

Just a thought, but I think I am getting stuck at this point in the installation:

"Start R GUI (Windows: start the R.exe, Linux: type "R" in console), open the file in the installation folder "install_packages.r", and run the code.".

The file "install_packages.r" does not exist anywhere on my hard drive. I assume this is an R script.

Thank you!

R version 3.2.2
Java 8.66

**Comment by jcolomb** [comment]
Hey. The r script you talk about is in the "installation" folfer. You missed (or I did) the point in the name ".r"

For the rgg runner, it is working only on machines with Java 6 and without 8,  and you need to use the zip version, not the exe.

Someone should shiny this, but I do not have the time now...

Best.
Julien

On 12 December 2015 02:04:59 CET, carabidus <notifications@github.com> wrote:
>Greetings,
>
>I got Buritrack to capture real-time data with wolf spiders, and now I
>would like to use the accompanying software for analysis
>
>I get this window for a few seconds when I run Rrrrunner, but then the
>program shuts down:
>![image](https://cloudgithubusercontentcom/assets/16169756/11759053/5d37a278-a041-11e5-8010-f32387583803png)
>
>Just a thought, but I think I am getting stuck at this point in the
>installation:
>
>"Start R GUI (Windows: start the Rexe, Linux: type "R" in console),
>open the file in the installation folder "install_packagesr", and run
>the code"
>
>The file "install_packagesr" does not exist anywhere on my hard drive I
>assume this is an R script
>
>Thank you!
>
>R version 322
>Java 866
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jcolomb/CeTrAn/issues/5

-- 
Envoyé de mon téléphone Android avec K-9 Mail. Excusez la brièveté.

**Comment by carabidus** [comment]
Thank you for the reply, Julien. I would be very interested in an updated rggrunner at some point. In the meanwhile, I will use the 'hexbin' package to plot occupancy of the arena. I am a bit new to this kind of analysis, so I would appreciate some advice. I have two treatment groups with my wolf spider study. I would like to know if the treated spiders are  utilizing/occupying the arena space differently than the control group. Is there a statistical test that would determine if such a difference exists?

**Comment by jcolomb** [comment]
hey, the R code can work without rgg: just find the master file and enter the variables by hand. you can open the rgg file with a text editor to understand what it does…

for the occupying different space, you should now exactly what is your test before you gather data, or make an initial study to find an hypothesis that you will test in a later one. time spent in your area of interest may be used, the centre area is often used for that, but check all water maze analysis to see other type of areas…

best
