### ISSUE TITLE
Can't unzip CeTrAn4.04.zip.

### ISSUE THREAD

**Issue by zn1993522** [jcolomb/CeTrAn#8]
Hi, I downloaded CeTrAn4.04 from https://sourceforge.net/projects/buridan/files/Analysis/, but when I opened the zip file, the WinRAR said that the file is broken. I tried another computer but the problem is the same. Does it work fine for you? Thanks.

**Comment by brembs** [comment]
I think I have uploaded the file a gazillion times and sometimes it works, sometimes not. I'm starting to think it's a sourceforge issue. I'll upload it again right away, but probably the best thing is to just download it from here. However, the tracker is not available from here, IIRC?

**Comment by brembs** [comment]
It works for me now...

**Comment by brembs** [comment]
I tried to upload the full ZIP to sourceforge and I keep getting an error message. The file works fine for me locally, so I have n idea why I'm getting an error message ("error zero").

**Comment by brembs** [comment]
Finally got a version to upload. 4.05 should work now.

**Comment by zn1993522** [comment]
CeTrAn4_05.zip worked well for me! Thanks so much!
