### ISSUE TITLE
Analysis with a smaller arena size

### ISSUE THREAD

**Issue by Lmatzeder** [jcolomb/CeTrAn#9]
I'm currently working with the tracking system of Buridan's Paradigm. In my experiment I'm using a roof to also test the behaviour in flies with wings. The roof has a diameter of 16mm, which is a lot smaller than the original platform in the Buridan (115mm). When I first analysed the data, the chart of speed was wrong, because I didn't set the smaller diameter of my arena in the tracking settings, so the tracking systems calculated the results refering to a diameter of 115mm. I analysed it again with the right settings and now i got a smaller transition plot which is too small to see anything. What else do I have to change to get both, the right chart of speed and the normal sized transition plot? 
Another issue i have with the analysis of centrophobism moving. I tested two groups of flies and the individual tests clearly show which group is more centrophobic. But the graph tells the opposite. Than i analysed the data only of moving flies, because in the more centrophobic group there where many flies which didn't move at all. As a result we got the graph that we expected. So could this also be caused by changing the size of the arena?

**Comment by jcolomb** [comment]
you could modify the gaussian value of the transition plot probably (weights = c(21,16,4,1)), or changing the axis in the plotting change 60 in 
	x = c(xy_table[xy_table$group==group_names[i],]$x,-60,60)
	y = c(xy_table[xy_table$group==group_names[i],]$y,-60,60)
	
	hbin = hexbin(x,y,xbins=60)

this should help
